- name: Install containerd
  apt:
    name: containerd
    force_apt_get: yes
    update_cache: yes

- name: Create directory for containerd configuration
  file:
    path: /etc/containerd
    state: directory

- name: Containerd configuration
  shell: containerd config default | sudo tee /etc/containerd/config.toml

- name: Modify containerd SystemdCgroup setting
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    line: 'SystemdCgroup = true'
    backup: yes

- name: Restart containerd
  command: systemctl restart containerd
