- name: Check if kubernetes config file exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: stat_result
      
- name: Join control plane to cluster
  command: "{{ hostvars['K8S_CONTROL_PLANE']['join_cluster_control'] }}"
  when: stat_result.stat.exists == False
