#- name: Add workers from inventory to /etc/hosts file
#  lineinfile:
#    dest: /etc/hosts
#    line: "{{ hostvars[item].ansible_host }} {{item}}"
#    state: present
#    backup: yes
#  when: hostvars[item].ansible_host is defined
#  with_items: "{{ groups.worker }}"

- name: Create directory for Kubernetes config
  file:
    path: /home/operator/.kube
    owner: operator
    group: operator
    state: directory
    mode: '0700'
