- hosts: master
  become: yes
  tasks:
    - include_tasks: tasks/k8s-prepare-master.yaml

- hosts: workers
  become: yes
  tasks:
    - include_tasks: tasks/k8s-prepare-worker.yaml

- hosts: all
  become: yes
  tasks:
    - include_tasks: tasks/k8s-prepare-all.yaml
