- hosts: init
  become: yes
  tasks:
    - include_tasks: tasks/k8s-install-init.yaml

- hosts: control_plane
  become: yes
  serial: 1
  tasks:
    - include_tasks: tasks/k8s-install-control-plane.yaml

- hosts: worker
  become: yes
  serial: 1
  tasks:
    - include_tasks: tasks/k8s-install-worker.yaml
