- hosts: init
  become: yes
  tasks:
    - include_tasks: tasks/add-operator-user.yaml
    - include_tasks: tasks/k8s-prepare-init.yaml

- hosts: init control_plane worker
  become: yes
  tasks:
    - include_tasks: tasks/k8s-add-repository.yaml
    - include_tasks: tasks/configure-cloud-init.yaml
    - include_tasks: tasks/install-container-runtime.yaml
    - include_tasks: tasks/k8s-prepare-all.yaml
