- hosts: master
  become: yes
  tasks:
    - name: Check if kubernetes config file exists
      stat:
        path: /etc/kubernetes/admin.conf
      register: stat_result

    - name: Copy initial configuration file
      template:
        src: k8s-init-config.yaml
        dest: /etc/kubernetes/k8s-init-config.yaml

    - name: Deploy kubernetes cluster if it was not deployed (base on presence of Kubernetes config file)
      shell: kubeadm init --config /etc/kubernetes/k8s-init-config.yaml
      when: stat_result.stat.exists == False

    - name: Copy Kubernetes config file to operator home directory
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /home/operator/.kube/config
        owner: operator
        group: operator
        mode: '0600'
    
    - name: Prepare command for joining worker to cluster
      command: "kubeadm token create --print-join-command"
      register: command_output
    - set_fact:
        join_cluster: "{{ command_output.stdout }}"
    - debug: msg="{{ join_cluster }}"
   
    - name: Register dummy host for storing command (to join worker to cluster)
      add_host:
         name: "K8S_WORKER"
         join_cluster: " {{ join_cluster }}"
    
- hosts: workers
  become: yes
  tasks:
    - name: Check if kubelet.conf file exists
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: stat_result

    - name: Join worker to cluster (depending on kubelet.conf file presence)
      command: "{{ hostvars['K8S_WORKER']['join_cluster'] }}"
      when: stat_result.stat.exists == False
