- hosts: control_plane
  become: yes
  tasks:
    - include_tasks: tasks/add-operator-user.yaml
    - include_tasks: tasks/k8s-prepare-control-plane.yaml

- hosts: workers
  become: yes
  tasks:
    - include_tasks: tasks/k8s-prepare-worker.yaml

- hosts: all
  become: yes
  tasks:
    - include_tasks: tasks/configure-cloud-init.yaml
    - include_tasks: tasks/install-container-runtime.yaml
    - include_tasks: tasks/k8s-prepare-all.yaml
